# Generated by Django 6.1.1 on 2026-09-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_message_messageadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageAdmin',
        ),
    ]
